context:
  name: "yggdrasil-python-rapidjson"
  version: "1.23.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/yggdrasil_python_rapidjson-${{ version }}.tar.gz
  sha256: f5d659e61ac5efd0a16fd8405961b69f7a6e89d4c39e1d16658cf03e84ee1860

build:
  number: 3
  script:
    - if: unix
      then:
        - 'CMAKE_GENERATOR="Ninja" ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
    - if: win
      then:
        - 'set "SKBUILD_CMAKE_ARGS=-G Ninja"'
        - '${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - numpy
        - python
    - cmake >=3.15
    - ninja
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - yggdrasil-rapidjson >=1.1.0.5
  host:
    - hatch-fancy-pypi-readme
    - numpy
    - pip
    - python
    - scikit-build-core
    - setuptools_scm
  run:
    - ${{ stdlib('c') }}
    - python
    - numpy

tests:
  - python:
      imports:
        - yggdrasil_rapidjson
  - script:
      - pytest -sv tests
    requirements:
      run:
        - pandas
        - pytest
        - pytz
        - trimesh
        - unyt
    files:
      source:
        - tests/

about:
  homepage: https://github.com/cropsinsilico/yggdrasil-python-rapidjson
  repository: https://github.com/cropsinsilico/yggdrasil-python-rapidjson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper around YggdrasilRapidJSON.
  description: |
    A Python wrapper around YggdrasilRapidJSON. YggdrasilRapidJSON is a
    header-only C++ library for JSON operation extended for use with
    yggdrasil
  documentation: https://cropsinsilico.github.io/yggdrasil-python-rapidjson

extra:
  recipe-maintainers:
    - langmm
